// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awpbkulsybdgourhgqyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3cGJrdWxzeWJkZ291cmhncXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzUwMDMsImV4cCI6MjA3MTgxMTAwM30.Tq1RFKUBjxNp84r_hOSE4DprpBSV-rjfWcOWFET31d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});